import os
import json
import uuid
import requests
from datetime import datetime
from dotenv import load_dotenv
load_dotenv()

SLACK_BOT_TOKEN = os.getenv("SLACK_BOT_TOKEN")
SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY")
FROM_EMAIL = os.getenv("FROM_EMAIL")
TEST_EMAIL = os.getenv("TEST_EMAIL")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")

def call_llm(prompt):
    try:
        url = "https://api.groq.com/openai/v1/chat/completions"
        headers = {"Authorization": f"Bearer {GROQ_API_KEY}", "Content-Type": "application/json"}
        data = {"model": "llama-3.3-70b-versatile", "messages": [{"role": "user", "content": prompt}]}
        response = requests.post(url, headers=headers, json=data)
        result = response.json()
        if "choices" in result and len(result["choices"]) > 0:
            return result["choices"][0]["message"]["content"]
        return None
    except Exception as e:
        print(f" LLM call failed: {e}")
        return None

def generate_marketing_copy(spec):
    value_prop = spec.get("value_proposition", "AI Email Reply Assistant")

    def ask(question):
        result = call_llm(
            f"Product: Smart ReplyAI — {value_prop}\n\n"
            f"{question}\n\n"
            f"Reply with ONLY the answer. No labels, no quotes, no explanation."
        )
        return result.strip().strip('"').strip("'") if result else None

    print(" Marketing copy generated by LLM")
    return {
        "tagline": ask("Write a product tagline under 10 words. Punchy and catchy.")
                   or "Reply smarter, not harder with AI",

        "short_description": ask("Write 2 sentences describing this product for a landing page. Focus on time savings.")
                              or "AI Email Reply Assistant drafts perfect responses in seconds. Save hours every week.",

        "email_subject": ask("Write a cold outreach email subject line under 10 words.")
                         or "Transform your email workflow with AI",

        "email_body": ask("Write a 3-paragraph cold outreach email. Professional tone. Do NOT use any placeholders like [First Name]. Start with 'Hi there,'. Sign off as LaunchMind Team. Plain text only.")
                      or "Hi there,\n\nAre you spending too much time on email replies?\n\nOur AI assistant drafts smart responses instantly.\n\nTry it free!\n\nBest regards,\nLaunchMind Team",

        "twitter_post": ask("Write a tweet under 200 chars for this product with hashtags #AI #Productivity.")
                        or " Meet AI Email Reply Assistant! Draft perfect replies in seconds. #AI #Productivity",

        "linkedin_post": ask("Write a 2-sentence LinkedIn post announcing this product.")
                         or "Excited to announce AI Email Reply Assistant — smart email responses instantly.",

        "instagram_post": ask("Write an Instagram caption with emojis and hashtags for this product.")
                          or " Let AI write your replies! #AIEmailAssistant #ProductivityHack",
    }

def send_email(subject, body, to_email):
    # Remove any leftover placeholders
    body = body.replace("[First Name]", "there")
    body = body.replace("[first name]", "there")

    try:
        url = "https://api.sendgrid.com/v3/mail/send"
        headers = {
            "Authorization": f"Bearer {SENDGRID_API_KEY}",
            "Content-Type": "application/json"
        }
        data = {
            "personalizations": [{"to": [{"email": to_email}]}],
            "from": {"email": FROM_EMAIL}, 
            "subject": subject,
            "content": [{"type": "text/plain", "value": body}]
        }
        r = requests.post(url, headers=headers, json=data, timeout=10)
        if r.status_code in [200, 202]:
            print(f" Email sent via SendGrid! Status: {r.status_code}")
            return True
        else:
            print(f" SendGrid failed ({r.status_code}): {r.text}, trying Gmail...")
    except Exception as e:
        print(f" SendGrid error: {e}, trying Gmail fallback...")

    # Fallback: Gmail SMTP
    try:
        import smtplib
        from email.mime.text import MIMEText
        from email.mime.multipart import MIMEMultipart

        gmail_user = os.getenv("GMAIL_USER")
        gmail_password = os.getenv("GMAIL_APP_PASSWORD")

        if not gmail_user or not gmail_password:
            print(" Gmail credentials not set in .env")
            return False

        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = gmail_user
        msg["To"] = to_email

        text_part = MIMEText(body, "plain")
        html_part = MIMEText(f"<p>{body}</p>", "html")
        msg.attach(text_part)
        msg.attach(html_part)

        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(gmail_user, gmail_password)
            server.sendmail(gmail_user, to_email, msg.as_string())

        print(" Email sent via Gmail SMTP!")
        return True

    except Exception as e:
        print(f" Gmail also failed: {e}")
        return False

def post_to_slack(tagline, description, pr_url):
    try:
        payload = {
            "channel": "#launches",
            "blocks": [
                {"type": "header", "text": {"type": "plain_text", "text": f" New Launch: {tagline}"}},
                {"type": "section", "text": {"type": "mrkdwn", "text": f"*AI Email Reply Assistant*\n{description}"}},
                {"type": "section", "fields": [
                    {"type": "mrkdwn", "text": f"*GitHub PR:* <{pr_url}|View PR>"},
                    {"type": "mrkdwn", "text": "*Status:* Ready for review"}
                ]},
                {"type": "divider"},
                {"type": "section", "text": {"type": "mrkdwn", "text": "_Posted by LaunchMind Marketing Agent"}}
            ]
        }
        r = requests.post("https://slack.com/api/chat.postMessage",
                          headers={"Authorization": f"Bearer {SLACK_BOT_TOKEN}"}, json=payload)
        result = r.json()
        if result.get("ok"):
            print("Slack message posted to #launches!")
        else:
            print(f"Slack failed: {result.get('error')}")
        return result.get("ok", False)
    except Exception as e:
        print(f"Slack error: {e}")
        return False

def marketing_agent(spec, pr_url, bus=None, skip_send=False):
    print("\n Marketing Agent starting...")

    copy = generate_marketing_copy(spec)

    email_sent = False
    slack_posted = False

    if not skip_send:
        email_sent = send_email(
            copy["email_subject"],
            copy["email_body"],
            TEST_EMAIL 
        )
        slack_posted = post_to_slack(copy["tagline"], copy["short_description"], pr_url)

    result_message = {
        "message_id": str(uuid.uuid4()),
        "from_agent": "marketing",
        "to_agent": "ceo",
        "message_type": "result",
        "payload": copy,
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "email_sent": email_sent,     
        "slack_posted": slack_posted   
    }

    if bus is not None:
        bus.send(result_message)
        print("--- Result sent to CEO via message bus ---")

    print("--- Marketing Agent done! ---")
    return result_message

if __name__ == "__main__":
    try:
        with open("product_spec.json", "r") as f:
            spec = json.load(f)
    except:
        spec = {"value_proposition": "AI email reply assistant", "personas": [], "features": [], "user_stories": []}
    marketing_agent(spec, "https://github.com/tooba393/AgenticAI_Assignment/pull/4")